name: Update Resume Gist

on: push

jobs:
  update-resume-gist:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: npm
      run: |
        # npm install -g resume-cli
        # npm install -g jsonresume-theme-macchiato
        
        # resume export resume.pdf --theme macchiato
        # resume export resume.html --theme macchiato

        npm install hacksalot/hackmyresume#dev -g

        npm install jsonresume-theme-macchiato
        # -g
        # git clone https://github.com/biosan/jsonresume-theme-macchiato

        # wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
        # sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb
        sudo apt-get -y install phantomjs

        hackmyresume build resume.json TO out/index.html out/resume.pdf -t node_modules/jsonresume-theme-macchiato
        # -t ${{ github.workspace }}/node_modules/jsonresume-theme-macchiato
        # -t macchiato

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "out"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
        
    # - name: Update Resume Gist
    #   uses: exuanbo/actions-deploy-gist@v1
    #   with:
    #     token: ${{ secrets.TOKEN }}
    #     gist_id: c9dcfa1b37dec07fb2ee7f36d7278105
    #     file_path: resume.json
